### ISSUE TITLE
The link for data, metadata, checkpoints cannot be accessed.

### ISSUE THREAD

**Issue by jshi31** [alirezazareian/vspnet#12]
As the title, can you update the link of them? Thanks

**Comment by alirezazareian** [comment]
I have checked the links and they seem to work. Please let me know what exactly the problem is. Is there a particular error page that you can describe? Those are public Dropbox links but you don't need a Dropbox account to download them.

**Comment by jshi31** [comment]
The link works now!

**Comment by jshi31** [comment]
Hi, I find the link for data, checkpoints are inaccessible again. I guess the link only keeps short term active and then expires again, and you may change the activity of this link. Here is the error I met.
![image](https://user-images.githubusercontent.com/38510289/98423773-afe50000-205d-11eb-972b-71dd278accc0.png)

**Comment by YiwuZhong** [comment]
I can't open the link either. It seems that your data storage isn't stable. Could you please double-check your link? Thanks!
