### ISSUE TITLE
Dropbox Links Not Working

### ISSUE THREAD

**Issue by arav-agarwal2** [alirezazareian/vspnet#37]
Hello,

The dropbox links containing the data, and checkpoints are not working.  Can we get some new links for this data?

**Comment by alirezazareian** [comment]
Hi, thank you for notifying me. It appears to be a temporary suspension due to high traffic volume on our Dropbox account. I will try to fix it or transfer the data to another host.

**Comment by alirezazareian** [comment]
The links should be working now!
