### ISSUE TITLE
Pretrained Model on OpenImage

### ISSUE THREAD

**Issue by zhaohengz** [alirezazareian/vspnet#8]
Hi,

Thanks for the wonderful work! 

May I ask where can I find the pretrained model that you guys took for feature extractor and proposal generator?

Thanks a lot for your help.

Best,
Zhaoheng

**Comment by alirezazareian** [comment]
I used [this tool](https://github.com/tensorflow/models/blob/master/research/object_detection/) to extract the proposals and features. More specifically, I used the checkpoint named `faster_rcnn_inception_resnet_v2_atrous_lowproposals_oidv2` from [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md) for the weakly supervised experiments, and `faster_rcnn_inception_resnet_v2_atrous_oidv2` for fully supervised. The only difference is the number of proposals that they generate.

**Comment by zhaohengz** [comment]
Thanks a lot for helping out! 

Best,
Zhaoheng

**Comment by zhaohengz** [comment]
Hi, 

Sorry for bothering again. 

I am trying to extract features and bounding boxes from the model. On which level do the boxes come from, the proposal level or after post-processing?

Thanks for helping out.

Best,
Zhaoheng

**Comment by yekeren** [comment]
I have the same question.

I guess they are from the proposal level. According to the pipeline.config from "http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_resnet_v2_atrous_lowproposals_oid_2018_01_28.tar.gz", the "first_stage_max_proposals" is already set to 20 ("max_total_detections" is also  20 though). The author responded to me in another thread saying that they use 20 proposals. So, I guess they use the 20 class-agnostic boxes from the proposal generation outputs.

**Comment by yekeren** [comment]
I've got the same question. Wish the authors to respond.

My guess is the average pooling(called in https://github.com/tensorflow/models/blob/72a31e9e5c06a663a8ee7ff7cc2a41e20557c9e5/research/object_detection/predictors/heads/class_head.py#L85) of the **predictions['box_classifier_features']** (aka, SecondStageFeatureExtractor/InceptionResnetV2/Conv2d_7b_1x1, shape=num_proposalsx8x8x1536)(https://github.com/tensorflow/models/blob/72a31e9e5c06a663a8ee7ff7cc2a41e20557c9e5/research/object_detection/meta_architectures/faster_rcnn_meta_arch.py#L1061). 

I am not sure which boxes are used (refined or not refined).
